// sim/main.cpp
// Verilator + SDL3 testbench for the GBC PPU
//
// What this does:
//   1. Instantiates the Verilated PPU model
//   2. Drives clk/rst and calls eval() each half-cycle
//   3. Decodes hsync/vsync/de/RGB555 signals - exactly as a real display would
//   4. Writes decoded pixels into an SDL3 streaming texture
//   5. Presents the texture to a window on every VSync
//
// RGB555 -> RGB888 expansion:
//   The GBC outputs 5 bits per channel. We expand to 8 bits by replicating
//   the top 3 bits into the bottom 3: val8 = (val5 << 3) | (val5 >> 2)
//   This gives a proper full-range expansion (31 -> 255, 0 -> 0).

#include "Vgbc.h"           // Generated by Verilator from gbc.v
#include "Vgbc___024root.h"
#include "verilated.h"

#include <SDL3/SDL.h>

#include <cstdint>
// #include <cstdio>
#include <iostream>
#include <iomanip>
#include <chrono>
#include <fstream>
#include <cmath>
using namespace std::chrono;
#include <memory>

#include <condition_variable>
#include <mutex>
#include <atomic>
#include <queue>
#include <thread>

// Python snippet using scipy.signal to design filters
/* 
from scipy import signal
filt = signal.iirdesign (
    wp = [20, 16e3],
    ws = [1, 20e3],
    gpass = 3,
    gstop = 20,
    analog = False,
    output = 'sos',
    fs = 4.1943e6
)
*/

class Biquad {
    double b0, b1, b2;
    double     a1, a2;
    double     x1, x2;
    double     y1, y2;
public:
    Biquad() = delete;
    Biquad(double b0, double b1, double b2, double a1, double a2);
    double filter(double x0);
};

#define SECTION0 Biquad( 0.00247977,-0.00495772, 0.00247977,-1.99753546, 0.998065  )
#define SECTION1 Biquad( 1.0       , 0.0       ,-1.0       ,-1.99308878, 0.99309236)
#define SECTION2 Biquad( 1.0       ,-1.99999998, 1.0       ,-1.99998686, 0.99998688)
#define SECTION3 Biquad( 1.0       , 0.0       , 0.0       , 0.0       , 0.0       )

// #define GBDOC_FILE "gbdoc.log"
// #define DEBUG
// #define BREAKPOINT
// #define TIME
// #define THREAD_AUDIO

// -------------------------------------------------------------------------
// Constants
// -------------------------------------------------------------------------
static constexpr double CLOCK_FRQ = 4.194304e6;

#ifdef TIME
static constexpr int CYCLE_INTERVAL = 1000;
#endif
static constexpr int GBC_W       = 160;   // GBC visible pixels per line
static constexpr int GBC_H       = 144;   // GBC visible lines
// static constexpr int SCALE       = 1;     // Window scale factor
// static constexpr int WIN_W       = GBC_W * SCALE;
// static constexpr int WIN_H       = GBC_H * SCALE;

// How many master-clock cycles to simulate before giving up if no frame arrives
static constexpr uint64_t GB_SEC = 4e6;
static constexpr uint64_t MAX_CYCLES = GB_SEC * 120;

static constexpr double cycles_per_sample = CLOCK_FRQ / 44.1e3;

static inline float d2a(uint8_t d) {
    // Maps the 6-bit dac values to analog values with 6'h00 -> -1.0 and 6'h3F ~> 1.0
    return ((static_cast<float>(d)/64.0f)-0.5f)*-2.0f;
}
#ifdef THREAD_AUDIO
struct audioFrame {
    uint8_t l;
    uint8_t r;
};

static std::queue<audioFrame> q;
static std::mutex m;
static std::condition_variable c;
static std::atomic<bool> keepRunning(true);

static void audio_thread(SDL_AudioStream* audio);
#endif
// -------------------------------------------------------------------------
// RGB555 -> RGB888 expansion helper
// -------------------------------------------------------------------------
static inline uint8_t expand5to8(uint8_t v5) {
    return static_cast<uint8_t>((v5 << 3) | (v5 >> 2));
}
// -------------------------------------------------------------------------
// main
// -------------------------------------------------------------------------
int main(int argc, char** argv) {
    #ifdef TIME
    auto start = high_resolution_clock::now();
    #endif
    // --- Verilator setup ---------------------------------------------------
    const std::unique_ptr<VerilatedContext> ctx{new VerilatedContext};
    float clk_period_half = ((1.0/CLOCK_FRQ)*std::pow(10, ctx->timeprecision()))/2.0;
    // VerilatedContext* ctx = new VerilatedContext;
    ctx->commandArgs(argc, argv);

    const std::unique_ptr<Vgbc> gbc{new Vgbc{ctx.get()}};
    // Vgbc* gbc = new Vgbc{ctx};
    #ifdef GBDOC_FILE
    #define REG_A gbc->rootp->System__DOT__Gameboy_SOC__DOT__cpu_core__DOT__regfile__DOT__r8_n[7]
    #define REG_B gbc->rootp->System__DOT__Gameboy_SOC__DOT__cpu_core__DOT__regfile__DOT__r8_n[0]
    #define REG_C gbc->rootp->System__DOT__Gameboy_SOC__DOT__cpu_core__DOT__regfile__DOT__r8_n[1]
    #define REG_D gbc->rootp->System__DOT__Gameboy_SOC__DOT__cpu_core__DOT__regfile__DOT__r8_n[2]
    #define REG_E gbc->rootp->System__DOT__Gameboy_SOC__DOT__cpu_core__DOT__regfile__DOT__r8_n[3]
    #define REG_F gbc->rootp->System__DOT__Gameboy_SOC__DOT__cpu_core__DOT__regfile__DOT__r8_n[6]
    #define REG_H gbc->rootp->System__DOT__Gameboy_SOC__DOT__cpu_core__DOT__regfile__DOT__r8_n[4]
    #define REG_L gbc->rootp->System__DOT__Gameboy_SOC__DOT__cpu_core__DOT__regfile__DOT__r8_n[5]
    #define RSP_H gbc->rootp->System__DOT__Gameboy_SOC__DOT__cpu_core__DOT__regfile__DOT__r8_n[10]
    #define RSP_L gbc->rootp->System__DOT__Gameboy_SOC__DOT__cpu_core__DOT__regfile__DOT__r8_n[11]
    #define RPC_H gbc->rootp->System__DOT__Gameboy_SOC__DOT__cpu_core__DOT__regfile__DOT__r8[8]
    #define RPC_L gbc->rootp->System__DOT__Gameboy_SOC__DOT__cpu_core__DOT__regfile__DOT__r8[9]
    #define ADDRB gbc->rootp->System__DOT__Gameboy_SOC__DOT__sig_cpu_addrbus
    #define ROM_D gbc->rootp->System__DOT__Cartridge__DOT__none_mbc__DOT__ROM
    #define RAM_D gbc->rootp->System__DOT__Cartridge__DOT__none_mbc__DOT__RAM
    #define WRAMS gbc->rootp->System__DOT__Gameboy_SOC__DOT__memory_access_controller__DOT__wram
    #define WBANK gbc->rootp->System__DOT__Gameboy_SOC__DOT__memory_access_controller__DOT__SVBK_reg
    #define BANKL gbc->rootp->System__DOT__Gameboy_SOC__DOT__memory_access_controller__DOT__BANK_lock
    #define PHASE gbc->rootp->System__DOT__Gameboy_SOC__DOT__cpu_core__DOT__cpu_phase
    #define FETCH gbc->rootp->System__DOT__Gameboy_SOC__DOT__cpu_core__DOT__controller__DOT__fetch
    #define INSTR gbc->rootp->System__DOT__Gameboy_SOC__DOT__cpu_core__DOT__controller__DOT__IR
    std::ofstream gbdoc_fstream(GBDOC_FILE);
    gbdoc_fstream << std::hex << std::setfill('0') << std::uppercase;
    #endif
    // --- SDL3 setup --------------------------------------------------------
    if (!SDL_Init(SDL_INIT_VIDEO | SDL_INIT_AUDIO)) {
        SDL_Log("SDL_Init failed: %s", SDL_GetError());
        return 1;
    }

    SDL_Window* window = SDL_CreateWindow(
        "GBC PPU Simulation",
        // WIN_W, WIN_H,
        GBC_W, GBC_H,
        SDL_WINDOW_RESIZABLE
    );
    if (!window) {
        SDL_Log("SDL_CreateWindow failed: %s", SDL_GetError());
        return 1;
    }

    SDL_Renderer* renderer = SDL_CreateRenderer(window, nullptr);
    if (!renderer) {
        SDL_Log("SDL_CreateRenderer failed: %s", SDL_GetError());
        return 1;
    }

    // Disable linear filtering so scaled pixels stay sharp
    SDL_SetRenderLogicalPresentation(renderer, GBC_W, GBC_H,
                                     SDL_LOGICAL_PRESENTATION_INTEGER_SCALE);

    // Streaming texture: we update it pixel-by-pixel as the PPU outputs them,
    // then blit it to the screen once per frame.
    // SDL_PIXELFORMAT_XRGB8888 = 0x00RRGGBB in memory (no alpha needed)
    SDL_Texture* texture = SDL_CreateTexture(
        renderer,
        SDL_PIXELFORMAT_XRGB8888,
        SDL_TEXTUREACCESS_STREAMING,
        GBC_W, GBC_H
    );
    if (!texture) {
        SDL_Log("SDL_CreateTexture failed: %s", SDL_GetError());
        return 1;
    }
    SDL_SetTextureScaleMode(texture, SDL_SCALEMODE_NEAREST);

    SDL_AudioSpec spec;
    spec.format = SDL_AUDIO_F32;
    spec.channels = 2;
    spec.freq = int(44.1e3);

    SDL_AudioStream* audio = SDL_OpenAudioDeviceStream(
        SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK, &spec, nullptr, nullptr
    );
    if (!audio) {
        SDL_Log("SDL_OpenAudioDeviceStream failed: %s", SDL_GetError());
        return 1;
    }
    SDL_ResumeAudioStreamDevice(audio);
    #ifdef THREAD_AUDIO
    std::thread audio_worker(audio_thread, audio);
    #else
    double sample_accumulator = 0.0;

    Biquad  l0 = SECTION0, r0 = SECTION0,
            l1 = SECTION1, r1 = SECTION1,
            l2 = SECTION2, r2 = SECTION2,
            l3 = SECTION3, r3 = SECTION3;

    float samples[256][2];
    uint8_t sample_idx = 0;
    #endif
    ctx->traceEverOn(true);

    // Pixel buffer - we write here and upload to the texture each VSync
    static uint32_t framebuf[GBC_W * GBC_H] = {};

    // --- Simulation state --------------------------------------------------
    // We track the previous values of hsync/vsync to detect edges
    uint8_t prev_hsync = 1;
    uint8_t prev_vsync = 1;

    uint8_t prev_sck = 0;
    int serial_counter = 0;
    unsigned char sdata = 0;

    // Current write position within the visible frame
    int cur_x = 0;
    int cur_y = 0;

    bool running    = true;
    bool in_vblank  = false;
    float seconds = 0;

    // --- Reset sequence ----------------------------------------------------
    // Hold reset for 4 cycles then release
    // gbc->done = 0;
    gbc->eval();
    ctx->timeInc(clk_period_half);
    gbc->clk = 0;
    gbc->rst = 1;
    gbc->sck_i = 0;
    gbc->sdi = 0;
    for (int i = 0; i < 8; i++) {
        gbc->clk ^= 1;
        gbc->eval();
        ctx->timeInc(clk_period_half);
    }
    gbc->rst = 0;
    
    #ifdef TIME
    auto end = high_resolution_clock::now();
    auto duration = duration_cast<microseconds>(end - start);
    std::cout   << "Initialization time: "
                << duration.count()
                << " us" << std::endl;
    #endif
    

    // --- Main simulation loop ----------------------------------------------
    bool done = false;
    uint64_t cycle = 0;
    std::cout << std::endl;
    int pixels_on_line = 0;
    uint64_t frame = 0;
    bool prefixed = false;
    while (running && cycle < MAX_CYCLES && !ctx->gotFinish()) {
    // while (running) {

        // Tick the clock (two eval() calls = one full master clock cycle)
        #ifdef TIME
        if ( cycle % CYCLE_INTERVAL == 0 ){
            start = high_resolution_clock::now();
        }
        #endif
        gbc->clk = 0; gbc->eval();
        #ifdef GBDOC_FILE
        if ( BANKL == 1 && PHASE == 0 && FETCH == 1 ){
            uint16_t SP = (RSP_H << 8) | RSP_L;
            // uint16_t PC = (RPC_H << 8) | RPC_L;
            uint16_t addr;
            uint16_t PCMEM0, PCMEM1, PCMEM2, PCMEM3;
            if ( ADDRB >= 0xD000 && ADDRB < 0xE000 ) {
                addr = ADDRB - 0xD000;
                if ( WBANK == 0 ) {
                    PCMEM0 = WRAMS[1][addr];
                    PCMEM1 = WRAMS[1][addr+1];
                    PCMEM2 = WRAMS[1][addr+2];
                    PCMEM3 = WRAMS[1][addr+3];
                }
                else {
                    PCMEM0 = WRAMS[WBANK][addr];
                    PCMEM1 = WRAMS[WBANK][addr+1];
                    PCMEM2 = WRAMS[WBANK][addr+2];
                    PCMEM3 = WRAMS[WBANK][addr+3];
                }
                
            }
            else if ( ADDRB >= 0xC000 && ADDRB < 0xD000 ) {
                addr = ADDRB - 0xC000;
                PCMEM0 = WRAMS[0][addr];
                PCMEM1 = WRAMS[0][addr+1];
                PCMEM2 = WRAMS[0][addr+2];
                PCMEM3 = WRAMS[0][addr+3];
            }
            else if ( ADDRB >= 0xA000 && ADDRB < 0xC000 ) {
                addr = ADDRB - 0xA000;
                PCMEM0 = RAM_D[addr];
                PCMEM1 = RAM_D[addr+1];
                PCMEM2 = RAM_D[addr+2];
                PCMEM3 = RAM_D[addr+3];
            } 
            else {
                PCMEM0 = ROM_D[ADDRB];
                PCMEM1 = ROM_D[ADDRB+1];
                PCMEM2 = ROM_D[ADDRB+2];
                PCMEM3 = ROM_D[ADDRB+3];
            }
            uint8_t instruction = PCMEM0;
            if ( !prefixed ) { // prefix
                gbdoc_fstream << "A:" << std::setw(2) << (int)REG_A << " F:" << std::setw(2) << (int)REG_F << 
                                " B:" << std::setw(2) << (int)REG_B << " C:" << std::setw(2) << (int)REG_C <<
                                " D:" << std::setw(2) << (int)REG_D << " E:" << std::setw(2) << (int)REG_E <<
                                " H:" << std::setw(2) << (int)REG_H << " L:" << std::setw(2) << (int)REG_L <<
                                " SP:" << std::setw(4) << SP    << " PC:" << std::setw(4) << (int)ADDRB <<
                                " PCMEM:" << 
                                std::setw(2) << PCMEM0 << "," << 
                                std::setw(2) << PCMEM1 << "," << 
                                std::setw(2) << PCMEM2 << "," << 
                                std::setw(2) << PCMEM3 <<
                                " TIME: " << (float)ctx->time() << std::endl; 
                // fprintf(gbdoc_f, "A:%02X F:%02X B:%02X C:%02X D:%02X E:%02X H:%02X L:%02X SP:%04X PC:%04X PCMEM:%02X,%02X,%02X,%02X CYCLE:%f\n",
                //     REG_A, REG_F, REG_B, REG_C, REG_D, REG_E, REG_H, REG_L, SP, ADDRB,
                //     PCMEM0, PCMEM1, PCMEM2, PCMEM3, seconds
                // );
            }
            if ( instruction == 0xCB && !prefixed ) { // SET 1 E has opcode 0xCB
                prefixed = true;
            }
            else {
                prefixed = false;
            }
        }
        #endif
        ctx->timeInc(clk_period_half); seconds += 1/4e6;
        gbc->clk = 1; gbc->eval();
        #ifdef TIME
        if ( cycle % CYCLE_INTERVAL == 0 ){
            end = high_resolution_clock::now();
            duration = duration_cast<microseconds>(end - start);
            std::cout   << "Cycle " << cycle << " time: "
                        << duration.count()
                        << " us" << std::endl;            
            start = high_resolution_clock::now();
        }
        #endif
        ctx->timeInc(clk_period_half); seconds += 1/4e6;

        // --- Decode outputs on the rising edge -------------------------
        #ifdef THREAD_AUDIO
        {
            std::lock_guard<std::mutex> lock(m);
            q.push(audioFrame{gbc->dac_l, gbc->dac_r});
        }
        c.notify_one();
        #else
        double l = l3.filter(l2.filter(l1.filter(l0.filter(d2a(gbc->dac_l)))));
        double r = r3.filter(r2.filter(r1.filter(r0.filter(d2a(gbc->dac_l)))));
        if ( sample_accumulator++ >= cycles_per_sample ) {
            sample_accumulator -= cycles_per_sample;
            samples[sample_idx  ][0] = static_cast<float>(l);
            samples[sample_idx++][1] = static_cast<float>(r);
            if ( sample_idx == 0 ) {
                SDL_PutAudioStreamData(audio, samples, sizeof(samples));
            }
        }
        #endif

        // Detect falling edge of vsync (active-low) = start of VBlank
        bool vsync_falling = (prev_vsync == 1) && (gbc->vsync == 0);
        // Detect rising edge of vsync = end of VBlank, new frame starting
        bool vsync_rising  = (prev_vsync == 0) && (gbc->vsync == 1);

        if (vsync_falling) {
            #ifdef DEBUG
            char buf[32];
            if ( snprintf(buf, 32, "./_out/frame/frame%d.ppm", frame++) > 0 ) {
                FILE* f = fopen(buf, "wb");
                fprintf(f, "P6\n%d %d\n255\n", GBC_W, GBC_H);
                for (int i = 0; i < GBC_W * GBC_H; i++) {
                    uint32_t px = framebuf[i];
                    uint8_t r = (px >> 16) & 0xFF, g = (px >> 8) & 0xFF, b = px & 0xFF;
                    fwrite(&r, 1, 1, f); fwrite(&g, 1, 1, f); fwrite(&b, 1, 1, f);
                }
                fclose(f);
            }
            #endif
            // VBlank just started: present the completed frame
            in_vblank = true;

            // Upload pixel buffer to the streaming texture
            void*  pixels_ptr;
            int    pitch;
            if (SDL_LockTexture(texture, nullptr, &pixels_ptr, &pitch)) {
                uint32_t* dst = static_cast<uint32_t*>(pixels_ptr);
                for (int row = 0; row < GBC_H; row++) {
                    uint32_t* row_dst = reinterpret_cast<uint32_t*>(
                        reinterpret_cast<uint8_t*>(dst) + row * pitch
                    );
                    uint32_t* row_src = &framebuf[row * GBC_W];
                    for (int col = 0; col < GBC_W; col++) {
                        row_dst[col] = row_src[col];
                        row_src[col] = 0;
                    }
                }
                SDL_UnlockTexture(texture);
            }

            // Render and present
            SDL_SetRenderDrawColor(renderer, 0, 0, 0, 255);
            SDL_RenderClear(renderer);
            SDL_RenderTexture(renderer, texture, nullptr, nullptr);
            SDL_RenderPresent(renderer);

            // Reset pixel write position for the new frame
            cur_x = 0;
            cur_y = 0;
            #ifdef DEBUG
            SDL_Log("End of frame");
            SDL_Event e;
            bool wait = true;
            while (wait) {
                if (SDL_WaitEvent(&e)) {
                    if (e.type == SDL_EVENT_QUIT) {
                        done = true;
                        running = false;
                        wait = false;
                    };
                    if (e.type == SDL_EVENT_KEY_DOWN) {
                        switch (e.key.key)
                        {
                        case SDLK_SPACE:
                            wait = false;
                            break;
                        default:
                            // continue
                            break;
                        }
                    }
                }
            }
            #endif
        }

        if (vsync_rising) {
            in_vblank = false;
        }

        // Write pixels when DE (data enable) is high
        if (gbc->de) {
            // pixels_on_line++;
            uint8_t r8 = expand5to8(gbc->r);
            uint8_t g8 = expand5to8(gbc->g);
            uint8_t b8 = expand5to8(gbc->b);

            // Pack as XRGB8888
            auto framebuf_idx = cur_y * GBC_W + cur_x;
            if ( framebuf_idx < GBC_H * GBC_W) {
                framebuf[cur_y * GBC_W + cur_x] =
                    (static_cast<uint32_t>(r8) << 16) |
                    (static_cast<uint32_t>(g8) <<  8) |
                    (static_cast<uint32_t>(b8));
            }
            cur_x++;
        }

        // Detect falling edge of hsync = end of active line, advance Y
        bool hsync_falling = (prev_hsync == 1) && (gbc->hsync == 0);
        if (hsync_falling) {
            cur_y++;
            cur_x = 0;
            // std::cout << pixels_on_line << std::endl;
            // pixels_on_line = 0;
        }

        prev_hsync = gbc->hsync;
        prev_vsync = gbc->vsync;

        bool sck_rising = (prev_sck == 0) && (gbc->sck_o == 1);
        if ( sck_rising ) {
            sdata = (sdata << 1) + gbc->sdo;
            serial_counter++;
        }

        prev_sck = gbc->sck_o;

        if ( serial_counter == 8 ) {
            std::cout << sdata << std::flush;
            sdata = 0;
            serial_counter = 0;
        }

        // --- SDL event handling (check every ~456 cycles = one scanline) ---
        if (cycle % 456 == 0) {
            SDL_Event e;
            while (SDL_PollEvent(&e)) {
                if (e.type == SDL_EVENT_QUIT){
                    running = false;
                    done = true;
                }
                if (e.type == SDL_EVENT_KEY_DOWN &&
                    e.key.key == SDLK_ESCAPE)
                    running = false;
            }
        }
        #ifdef BREAKPOINT
        if ( gbc->dbg_break ) {
            SDL_Log("Breakpoint hit");
            SDL_Event e;
            bool wait = true;
            while (wait) {
                if (SDL_WaitEvent(&e)) {
                    if (e.type == SDL_EVENT_QUIT) {
                        done = true;
                        running = false;
                        wait = false;
                    };
                    if (e.type == SDL_EVENT_KEY_DOWN) {
                        switch (e.key.key)
                        {
                        case SDLK_ESCAPE:
                            running = false;
                            done = true;
                        case SDLK_SPACE:
                            wait = false;
                            break;
                        default:
                            // continue
                            break;
                        }
                    }
                }
            }
        }
        # endif
        #ifdef TIME
        if ( cycle % CYCLE_INTERVAL == 0 ){
            end = high_resolution_clock::now();
            duration = duration_cast<microseconds>(end - start);
            std::cout   << "Decode " << cycle << " time: "
                        << duration.count()
                        << " us" << std::endl;
        }
        #endif
        cycle++;
    }
    std::cout << std::endl;

    #ifdef GBDOC_FILE
    // fclose(gbdoc_f);
    gbdoc_fstream.close();
    #endif

    if (!done) {
        if (ctx->gotFinish()) {
            SDL_Log("Simulation ended with $finish");
        }
        else if (cycle >= MAX_CYCLES){
            SDL_Log("Simulation ended: MAX_CYCLES reached");
            SDL_Event e;
            while (true) {
                SDL_PollEvent(&e);
                if (e.type == SDL_EVENT_QUIT)
                    break;
                if (e.type == SDL_EVENT_KEY_DOWN &&
                    e.key.key == SDLK_ESCAPE)
                    break;
            }
        }
    }
    // --- Cleanup -----------------------------------------------------------
    // gbc->eval();
    // gbc->done = 1;
    // gbc->eval();

    gbc->final();

    ctx->statsPrintSummary();
    #ifdef THREAD_AUDIO
    keepRunning.store(false);
    c.notify_all();
    audio_worker.join();
    #endif

    SDL_DestroyTexture(texture);
    SDL_DestroyRenderer(renderer);
    SDL_DestroyWindow(window);
    SDL_Quit();

    return 0;
}

Biquad::Biquad(double b0, double b1, double b2, double a1, double a2) : 
    b0(b0), b1(b1), b2(b2), a1(a1), a2(a2) {
    x1 = 0;
    x2 = 0;
    y1 = 0;
    y2 = 0;
}

inline double Biquad::filter(double x0) {
    double y0 = (b0*x0) + (b1*x1) + (b2*x2) - (a1*y1) - (a2*y2);
    x2 = x1; x1 = x0;
    y2 = y1; y1 = y0;
    return y0;
}

#ifdef THREAD_AUDIO
void audio_thread(SDL_AudioStream *audio) {
    double sample_accumulator = 0.0;

    Biquad  l0 = SECTION0, r0 = SECTION0,
            l1 = SECTION1, r1 = SECTION1,
            l2 = SECTION2, r2 = SECTION2,
            l3 = SECTION3, r3 = SECTION3;

    float samples[256][2];
    uint8_t sample_idx = 0;


    while (keepRunning.load()) {
        audioFrame f;
        {
            std::unique_lock<std::mutex> lock(m);
            c.wait(lock, []() { return !q.empty() || !keepRunning.load(); });
            if ( !keepRunning.load() ) {
                break;
            }
            f = q.front();
            q.pop();  
        }
        double l = l3.filter(l2.filter(l1.filter(l0.filter(d2a(f.l)))));
        double r = r3.filter(r2.filter(r1.filter(r0.filter(d2a(f.r)))));
        if ( sample_accumulator++ >= cycles_per_sample ) {
            sample_accumulator -= cycles_per_sample;
            samples[sample_idx  ][0] = static_cast<float>(l);
            samples[sample_idx++][1] = static_cast<float>(r);
            if ( sample_idx == 0 ) {
                SDL_PutAudioStreamData(audio, samples, sizeof(samples));
            }
        }
    }
}
#endif