// sim/main.cpp
// Verilator + SDL3 testbench for the GBC PPU
//
// What this does:
//   1. Instantiates the Verilated PPU model
//   2. Drives clk/rst and calls eval() each half-cycle
//   3. Decodes hsync/vsync/de/RGB555 signals - exactly as a real display would
//   4. Writes decoded pixels into an SDL3 streaming texture
//   5. Presents the texture to a window on every VSync
//
// RGB555 -> RGB888 expansion:
//   The GBC outputs 5 bits per channel. We expand to 8 bits by replicating
//   the top 3 bits into the bottom 3: val8 = (val5 << 3) | (val5 >> 2)
//   This gives a proper full-range expansion (31 -> 255, 0 -> 0).

#include "Vgbc.h"           // Generated by Verilator from gbc.v
#include "verilated.h"

#include <SDL3/SDL.h>

#include <cstdint>
// #include <cstdio>
#include <iostream>
#include <chrono>
using namespace std::chrono;
#include <memory>

// -------------------------------------------------------------------------
// Display constants
// -------------------------------------------------------------------------
static constexpr int GBC_W       = 160;   // GBC visible pixels per line
static constexpr int GBC_H       = 144;   // GBC visible lines
static constexpr int SCALE       = 4;     // Window scale factor
static constexpr int WIN_W       = GBC_W * SCALE;
static constexpr int WIN_H       = GBC_H * SCALE;

// How many master-clock cycles to simulate before giving up if no frame arrives
// static constexpr uint64_t MAX_CYCLES = 8e6;  // ~2 seconds of GBC time
static constexpr uint64_t MAX_CYCLES = 8e5;
static constexpr uint64_t CYCLE_INTERVAL = long(1e7);
static constexpr int clk_period_half = int(((1/4e6)*1e12)/2);

// -------------------------------------------------------------------------
// RGB555 -> RGB888 expansion helper
// -------------------------------------------------------------------------
static inline uint8_t expand5to8(uint8_t v5) {
    return static_cast<uint8_t>((v5 << 3) | (v5 >> 2));
}

// -------------------------------------------------------------------------
// main
// -------------------------------------------------------------------------
int main(int argc, char** argv) {
    auto start = high_resolution_clock::now();
    // --- Verilator setup ---------------------------------------------------
    const std::unique_ptr<VerilatedContext> ctx{new VerilatedContext};
    ctx->commandArgs(argc, argv);

    const std::unique_ptr<Vgbc> gbc{new Vgbc{ctx.get()}};

    // --- SDL3 setup --------------------------------------------------------
    if (!SDL_Init(SDL_INIT_VIDEO)) {
        SDL_Log("SDL_Init failed: %s", SDL_GetError());
        return 1;
    }

    SDL_Window* window = SDL_CreateWindow(
        "GBC PPU Simulation",
        WIN_W, WIN_H,
        0   // no special flags needed
    );
    if (!window) {
        SDL_Log("SDL_CreateWindow failed: %s", SDL_GetError());
        return 1;
    }

    SDL_Renderer* renderer = SDL_CreateRenderer(window, nullptr);
    if (!renderer) {
        SDL_Log("SDL_CreateRenderer failed: %s", SDL_GetError());
        return 1;
    }

    // Disable linear filtering so scaled pixels stay sharp
    SDL_SetRenderLogicalPresentation(renderer, GBC_W, GBC_H,
                                     SDL_LOGICAL_PRESENTATION_INTEGER_SCALE);

    // Streaming texture: we update it pixel-by-pixel as the PPU outputs them,
    // then blit it to the screen once per frame.
    // SDL_PIXELFORMAT_XRGB8888 = 0x00RRGGBB in memory (no alpha needed)
    SDL_Texture* texture = SDL_CreateTexture(
        renderer,
        SDL_PIXELFORMAT_XRGB8888,
        SDL_TEXTUREACCESS_STREAMING,
        GBC_W, GBC_H
    );
    if (!texture) {
        SDL_Log("SDL_CreateTexture failed: %s", SDL_GetError());
        return 1;
    }
    SDL_SetTextureScaleMode(texture, SDL_SCALEMODE_NEAREST);

    ctx->traceEverOn(true);

    // Pixel buffer - we write here and upload to the texture each VSync
    static uint32_t framebuf[GBC_W * GBC_H] = {};

    // --- Simulation state --------------------------------------------------
    // We track the previous values of hsync/vsync to detect edges
    uint8_t prev_hsync = 1;
    uint8_t prev_vsync = 1;

    uint8_t prev_sck = 0;
    int serial_counter = 0;
    char sdata = 0;

    // Current write position within the visible frame
    int cur_x = 0;
    int cur_y = 0;

    bool running    = true;
    bool in_vblank  = false;

    // --- Reset sequence ----------------------------------------------------
    // Hold reset for 4 cycles then release
    // gbc->done = 0;
    gbc->clk = 0;
    gbc->rst = 1;
    gbc->sck_i = 0;
    gbc->sdi = 0;
    for (int i = 0; i < 8; i++) {
        gbc->clk ^= 1;
        ctx->timeInc(clk_period_half);
        gbc->eval();
    }
    gbc->rst = 0;
    
    auto end = high_resolution_clock::now();
    auto duration = duration_cast<microseconds>(end - start);
    // std::cout   << "Initialization time: "
    //             << duration.count()
    //             << " us" << std::endl;

    

    // --- Main simulation loop ----------------------------------------------
    uint64_t cycle = 0;
    std::cout << std::endl;

    while (running && cycle < MAX_CYCLES) {
    // while (running) {

        // Tick the clock (two eval() calls = one full master clock cycle)
        // if ( cycle % CYCLE_INTERVAL == 0 ){
        //     start = high_resolution_clock::now();
        // }
        gbc->clk = 0; gbc->eval();
        ctx->timeInc(clk_period_half);
        gbc->clk = 1; gbc->eval();
        // if ( cycle % CYCLE_INTERVAL == 0 ){
        //     end = high_resolution_clock::now();
        //     duration = duration_cast<microseconds>(end - start);
        //     std::cout   << "Cycle " << cycle << " time: "
        //                 << duration.count()
        //                 << " us" << std::endl;            
        //     start = high_resolution_clock::now();
        // }
        ctx->timeInc(clk_period_half);

        // --- Decode PPU outputs on the rising edge -------------------------

        // Detect falling edge of vsync (active-low) = start of VBlank
        bool vsync_falling = (prev_vsync == 1) && (gbc->vsync == 0);
        // Detect rising edge of vsync = end of VBlank, new frame starting
        bool vsync_rising  = (prev_vsync == 0) && (gbc->vsync == 1);

        if (vsync_falling) {
            // VBlank just started: present the completed frame
            in_vblank = true;

            // Upload pixel buffer to the streaming texture
            void*  pixels_ptr;
            int    pitch;
            if (SDL_LockTexture(texture, nullptr, &pixels_ptr, &pitch)) {
                uint32_t* dst = static_cast<uint32_t*>(pixels_ptr);
                for (int row = 0; row < GBC_H; row++) {
                    uint32_t* row_dst = reinterpret_cast<uint32_t*>(
                        reinterpret_cast<uint8_t*>(dst) + row * pitch
                    );
                    const uint32_t* row_src = &framebuf[row * GBC_W];
                    for (int col = 0; col < GBC_W; col++)
                        row_dst[col] = row_src[col];
                }
                SDL_UnlockTexture(texture);
            }

            // Render and present
            SDL_SetRenderDrawColor(renderer, 0, 0, 0, 255);
            SDL_RenderClear(renderer);
            SDL_RenderTexture(renderer, texture, nullptr, nullptr);
            SDL_RenderPresent(renderer);

            // Reset pixel write position for the new frame
            cur_x = 0;
            cur_y = 0;
        }

        if (vsync_rising) {
            in_vblank = false;
        }

        // Write pixels when DE (data enable) is high and we're not in VBlank
        if (gbc->de && !in_vblank) {
            if (cur_x < GBC_W && cur_y < GBC_H) {
                uint8_t r8 = expand5to8(gbc->r);
                uint8_t g8 = expand5to8(gbc->g);
                uint8_t b8 = expand5to8(gbc->b);

                // Pack as XRGB8888
                framebuf[cur_y * GBC_W + cur_x] =
                    (static_cast<uint32_t>(r8) << 16) |
                    (static_cast<uint32_t>(g8) <<  8) |
                    (static_cast<uint32_t>(b8));

                cur_x++;
            }
        }

        // Detect falling edge of hsync = end of active line, advance Y
        bool hsync_falling = (prev_hsync == 1) && (gbc->hsync == 0);
        if (hsync_falling && !in_vblank) {
            cur_y++;
            cur_x = 0;
        }

        prev_hsync = gbc->hsync;
        prev_vsync = gbc->vsync;

        bool sck_rising = (prev_sck == 0) && (gbc->sck_o == 1);
        if ( sck_rising ) {
            sdata = (sdata << 1) + gbc->sdo;
            serial_counter++;
        }

        prev_sck = gbc->sck_o;

        if ( serial_counter == 8 ) {
            std::cout << sdata << std::flush;
            sdata = 0;
            serial_counter = 0;
        }

        // --- SDL event handling (check every ~456 cycles = one scanline) ---
        if (cycle % 456 == 0) {
            SDL_Event e;
            while (SDL_PollEvent(&e)) {
                if (e.type == SDL_EVENT_QUIT)
                    running = false;
                if (e.type == SDL_EVENT_KEY_DOWN &&
                    e.key.key == SDLK_ESCAPE)
                    running = false;
            }
        }

        
        // if ( cycle % CYCLE_INTERVAL == 0 ){
        //     end = high_resolution_clock::now();
        //     duration = duration_cast<microseconds>(end - start);
        //     std::cout   << "Decode " << cycle << " time: "
        //                 << duration.count()
        //                 << " us" << std::endl;
        // }
        cycle++;
    }
    std::cout << std::endl;

    if (cycle >= MAX_CYCLES)
        SDL_Log("Simulation ended: MAX_CYCLES reached");

    // --- Cleanup -----------------------------------------------------------
    // gbc->eval();
    // gbc->done = 1;
    // gbc->eval();

    gbc->final();

    ctx->statsPrintSummary();

    SDL_DestroyTexture(texture);
    SDL_DestroyRenderer(renderer);
    SDL_DestroyWindow(window);
    SDL_Quit();

    return 0;
}
