?program		:	line_list
line_list		:	_line+
_line			:	SH_COMMENT
				|	instruction
				|	label
				|	_label_inst

_label_inst		:	label instruction
label			:	LABEL
LABEL.-1		: 	CNAME ":"

instruction		:	_mnemonic SH_COMMENT?
_mnemonic		:	increment
				|	decrement
				|	jump_rel
				|	load_r8_r8
				|	load_imm16
				|	load_imm8
				|	load_r16_a
				|	load_a_r16
				|	load_dir_sp
				|	add_hl_r16
				|	jump_rel_cd
				|	add_a_r8
				|	adc_a_r8
				|	sub_a_r8
				|	sbc_a_r8
				|	and_a_r8
				|	xor_a_r8
				|	or_a_r8
				|	cp_a_r8
				|	NOP
				|	RLCA
				|	RRCA
				|	RLA
				|	RRA
				|	DAA
				|	CPL
				|	SCF
				|	CCF
				|	STOP
				|	HALT

increment		:	INC (r16 | r8)
decrement		:	DEC (r16 | r8)
jump_rel		:	JR (_imm | CNAME)

load_r8_r8		:	LD r8 ","? r8
load_imm16		:	LD r16 ","? _imm
load_imm8		:	LD r8 ","? _imm
load_r16_a		:	LD "[" r16mem "]" ","? A
load_a_r16		:	LD A ","? "[" r16mem "]"
load_dir_sp		:	LD _direct ","? SP
add_hl_r16		:	ADD HL ","? r16
add_a_r8		:	ADD A ","? r8
adc_a_r8		:	ADC A ","? r8
sub_a_r8		:	SUB A ","? r8
sbc_a_r8		:	SBC A ","? r8
and_a_r8		:	AND A ","? r8
xor_a_r8		:	XOR A ","? r8
or_a_r8			:	OR A ","? r8
cp_a_r8			:	CP A ","? r8
jump_rel_cd		:	JR COND ","? (_imm | CNAME)

NOP				:	"nop"
STOP			:	"stop"
HALT			:	"halt"
RLCA			:	"rlca"
RRCA			:	"rrca"
RLA				:	"rla"
RRA				:	"rra"
DAA				:	"daa"
CPL				:	"cpl"
SCF				:	"scf"
CCF				:	"ccf"
INC				:	"inc"
DEC				:	"dec"
JR				:	"jr"
LD				:	"ld"
ADD				:	"add"
ADC				:	"adc"
SUB				:	"sub"
SBC				:	"sbc"
AND				:	"and"
XOR				:	"xor"
OR				:	"or"
CP				:	"cp"

_direct			: 	"[" _imm "]"

r8				: 	B |	C |	D |	E |	H |	L | HLR8 | A
B				:	"b"i
C				:	"c"i
D				:	"d"i
E				:	"e"i
H				:	"h"i
L				:	"l"i
HLR8			:	"[hl]"i
A				:	"a"i

r16				:	BC | DE	| HL | SP
r16mem			:	BC | DE | HLI | HLD
BC				:	"bc"i
DE				:	"de"i
HL				:	"hl"i
SP				:	"sp"i
HLI				:	"hl+"i | "hli"i
HLD				:	"hl-"i | "hld"i

COND			:	"z"i
				| 	"nz"i
				| 	"c"i
				| 	"nc"i

_imm			:	DECNUM | _hex | _bin
DECNUM			:	INT | SIGNED_INT
_hex			:	"0x" HEXNUM
HEXNUM			:	HEXDIGIT+
_bin			:	"0b" BINNUM
BINNUM			:	("0" | "1")+

ASM_COMMENT: /;[^\n]*/

%import common.DIGIT
%import common.HEXDIGIT
%import common.INT
%import common.SIGNED_INT
%import common.SH_COMMENT
%import common.WS
%import common.NEWLINE
%import common.CNAME
%ignore SH_COMMENT
%ignore ASM_COMMENT
%ignore WS